>>> lat_dim value: 60
>>> mode is: jonatank
(780, 666)
CAME HERE!! 1
CAME HERE!! 11
2020-09-30 19:11:04.209427: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-30 19:11:04.376046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:83:00.0
totalMemory: 11.91GiB freeMemory: 11.77GiB
2020-09-30 19:11:04.376080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:11:04.840217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:11:04.840256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:11:04.840263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:11:04.840476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:83:00.0, compute capability: 6.1)
2020-09-30 19:11:04.841289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:11:04.841314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:11:04.841322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:11:04.841327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:11:04.841458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:83:00.0, compute capability: 6.1)
True
CAME HERE!! 12
CAME HERE!! 2
CAME HERE!! 3
CAME HERE!! 31
CAME HERE!! 32
Initialized parameters
CAME HERE!! 33
CAME HERE!! 4
Step 0 | L2 Loss: -127.713 | KLD Loss: 0.004 | L2 Loss_1: 248.000 | L2 Loss_2: 375.713 | loss_tot: -55.590 | L2 Loss test: 149.462
Traceback (most recent call last):
  File "train_vae.py", line 313, in <module>
    batch = MRi.get_patch(batch_size, test=False)
  File "/scratch_net/bmicdl03/jonatank/code/ddp/dataloader.py", line 116, in get_patch
    with h5py.File(self.dirname + '/multicoil_train_old3/' + file, 'r') as fdset:
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (truncated file: eof = 369178112, sblock->base_addr = 0, stored_eof = 372751856)
