>>> lat_dim value: 60
>>> mode is: jonatank
(780, 666)
CAME HERE!! 1
CAME HERE!! 11
2020-09-30 19:37:21.809192: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-30 19:37:22.221393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:05:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-09-30 19:37:22.221451: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:37:28.089155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:37:28.089726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:37:28.089746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:37:28.090046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10419 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2020-09-30 19:37:28.091496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:37:28.091534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:37:28.091550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:37:28.091562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:37:28.092203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 10419 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
True
CAME HERE!! 12
CAME HERE!! 2
CAME HERE!! 3
CAME HERE!! 31
CAME HERE!! 32
Initialized parameters
CAME HERE!! 33
CAME HERE!! 4
Step 0 | L2 Loss: -111.229 | KLD Loss: 0.004 | L2 Loss_1: 257.807 | L2 Loss_2: 369.035 | loss_tot: -61.029 | L2 Loss test: 144.317
Step 10 | L2 Loss: -1963.923 | KLD Loss: 0.057 | L2 Loss_1: 159.066 | L2 Loss_2: 2122.990 | loss_tot: -949.125 | L2 Loss test: 9.634
Traceback (most recent call last):
  File "train_vae.py", line 313, in <module>
    batch = MRi.get_patch(batch_size, test=False)
  File "/scratch_net/bmicdl03/jonatank/code/ddp/dataloader.py", line 116, in get_patch
    with h5py.File(self.dirname + '/multicoil_train_old3/' + file, 'r') as fdset:
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (truncated file: eof = 369178112, sblock->base_addr = 0, stored_eof = 372751856)
