>>> lat_dim value: 60
>>> mode is: jonatank
CAME HERE!! 1
CAME HERE!! 11
2020-10-01 09:58:51.680931: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-01 09:58:51.900624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:04:00.0
totalMemory: 10.73GiB freeMemory: 10.57GiB
2020-10-01 09:58:51.900663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-10-01 09:58:57.955830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-01 09:58:57.956647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-10-01 09:58:57.956676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-10-01 09:58:57.957009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10203 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-10-01 09:58:57.958048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-10-01 09:58:57.958076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-01 09:58:57.958086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-10-01 09:58:57.958094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-10-01 09:58:57.958267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 10203 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
True
CAME HERE!! 12
CAME HERE!! 2
CAME HERE!! 3
CAME HERE!! 31
CAME HERE!! 32
Initialized parameters
CAME HERE!! 33
CAME HERE!! 4
Step 0 | L2 Loss: -119.648 | KLD Loss: 0.004 | L2 Loss_1: 257.463 | L2 Loss_2: 377.111 | loss_tot: -58.337 | L2 Loss test: 146.204
Step 10 | L2 Loss: -1890.959 | KLD Loss: 0.022 | L2 Loss_1: 155.017 | L2 Loss_2: 2045.975 | loss_tot: -933.772 | L2 Loss test: 9.376
Traceback (most recent call last):
  File "train_vae.py", line 313, in <module>
    batch = MRi.get_patch(batch_size, test=False)
  File "/scratch_net/bmicdl03/jonatank/code/ddp/dataloader.py", line 79, in get_patch
    with h5py.File(self.dirname + '/multicoil_train_old3/' + file, 'r') as fdset:
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (truncated file: eof = 369178112, sblock->base_addr = 0, stored_eof = 372751856)
